### ISSUE TITLE
GET with parameters acts as a POST

### ISSUE THREAD

**Issue by spemberton** [cwi-dis/igor#11]
If you do 
  GET sandbox/list?item=foo
it POSTS 
  <list><item>foo</item></list>
instead.
class AbstractDatabaseAccess(object):
    def GET(self, name):
        """If no query get the content of a section of the database.
        If there is a query can be used as a 1-url shortcut for POST."""

**Comment by jackjansen** [comment]
Fixed in b20a2d0
