### ISSUE TITLE
'future' has to be installed first, before requirements.txt (using.md)

### ISSUE THREAD

**Issue by spemberton** [cwi-dis/igor#16]
If I try to sudo pip3 install -r requirements.txt, it fails with ImportError: No module named 'future'
If I do an install future, and then install requirements.txt, it works.

$ sudo pip3 install -r requirements.txt
The directory '/home/steven/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/steven/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting future (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz (829kB)
    100% |████████████████████████████████| 829kB 14.5MB/s 
Requirement already satisfied: httplib2 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (0.9.1)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (2.9.1)
Collecting flask>=1.0 (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/7f/e7/08578774ed4536d3242b14dacb4696386634607af824ea997202cd0edb4b/Flask-1.0.2-py2.py3-none-any.whl (91kB)
    100% |████████████████████████████████| 92kB 21.9MB/s 
Collecting gevent (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/87/c4/9afb40b4a8b9186787d477aa6ebcfa17ead40ecbf83d5a1ed53dadd4f6ef/gevent-1.3.7-cp35-cp35m-manylinux1_x86_64.whl (4.4MB)
    100% |████████████████████████████████| 4.4MB 13.6MB/s 
Collecting python-dateutil (from -r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/74/68/d87d9b36af36f44254a8d512cbfc48369103a3b9e474be9bdfe536abfc45/python_dateutil-2.7.5-py2.py3-none-any.whl (225kB)
    100% |████████████████████████████████| 235kB 17.8MB/s 
Collecting py-dom-xpath-six (from -r requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/c1/b0/d2a12b93b90e648ef7e6e0e88d631720678dba2beedb9133057d932a144b/py-dom-xpath-six-0.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-24zg6rfo/py-dom-xpath-six/setup.py", line 13, in <module>
        import yapps2
      File "yapps2/yapps2.py", line 32, in <module>
        from future import standard_library
    ImportError: No module named 'future'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-24zg6rfo/py-dom-xpath-six/

**Comment by jackjansen** [comment]
I think this is actually an issue with https://github.com/jackjansen/py-dom-xpath-six (missing dependency). I will investigate.

**Comment by jackjansen** [comment]
Should be fixed in https://github.com/jackjansen/py-dom-xpath-six/tree/0.2.2. Can you confirm and close?

**Comment by jackjansen** [comment]
Actually confirmed it myself:-)
