### ISSUE TITLE
Router IP address should be configurable

### ISSUE THREAD

**Issue by spemberton** [cwi-dis/igor#17]
I get this message in /data:

&lt;router>
   router is not available (timeout connecting to 192.168.1.1)
&lt;/router>

However, my router is at another address. That address should be a value within /data

**Comment by jackjansen** [comment]
This is an instance of a more general problem: multifunctional plugins, like _lan_, need their own configuration UI.

The underlying mechanisms to allow this are already in place: plugins can have multiple entrypoints (in the `igorplugin.py` module) and they can have HTML template documents. If you look at the *_fitbit* plugin you can see how this is used there to add your OAuth2 fitbit credentials and add Igor users that are also fitbit users.

I'm thinking that if a plugin has a `setup.html` template the user adding the plugin will be directed there when installing the plugin, so they can finish off the installation (for example by saying whether they want _lan_ to check their router, and provide the IP address if they do).

Can you come up with some user journeys that would work here?
